  name: Deploy to Azure

  on:
    push:
      branches:
        - master

  jobs:
    deploy_dev:
      uses: ./.github/workflows/vnet_deployment.yml@master
      with:
        environment: 'dev'
        resource_group_name: 'RG_OLLAMA_DEV_VNET'
        location: 'West Europe'
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
        client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}

    deploy_prod:
      needs: deploy_dev
      uses: ./.github/workflows/vnet_deployment.yml@master
      with:
        environment: 'prod'
        resource_group_name: 'RG_OLLAMA_PROD_VNET'
        location: 'West Europe'
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
        client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
