name: Azure Deployment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment (dev or prod)'
        required: true
        type: string
      resource_group_name:
        description: 'Azure Resource Group Name'
        required: true
        type: string
      location:
        description: 'Azure Region'
        required: true
        type: string
      client_id:
        description: 'Azure Service Principal Client ID'
        required: true
        type: string
      client_secret:
        description: 'Azure Service Principal Client Secret'
        required: true
        type: string
      tenant_id:
        description: 'Azure Tenant ID'
        required: true
        type: string
    secrets:
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1

      - name: Azure Login
        run: |
          az login --service-principal -u ${{ inputs.client_id }} -p ${{ inputs.client_secret }} --tenant ${{ inputs.tenant_id }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.11.2'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
