  name: Azure Deployment

  on:
    workflow_call:
      inputs:
        environment:
          description: 'Deployment environment (dev or prod)'
          required: true
        resource_group_name:
          description: 'Azure Resource Group Name'
          required: true
        location:
          description: 'Azure Region'
          required: true
      secrets:
        client_id:
          description: 'Azure Service Principal Client ID'
          required: true
        client_secret:
          description: 'Azure Service Principal Client Secret'
          required: true
        tenant_id:
          description: 'Azure Tenant ID'
          required: true

  jobs:
    deploy:
      runs-on: self-hosted
      environment: ${{ inputs.environment }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Azure CLI
          uses: azure/setup-azurecli@v1

        - name: Azure Login
          run: |
            az login --service-principal -u ${{ inputs.client_id }} -p ${{ inputs.client_secret }} --tenant ${{ inputs.tenant_id }}
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Install Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: '1.11.2'

        - name: Terraform Init
          run: terraform init

        - name: Terraform Validate
          run: terraform validate

        - name: Terraform Plan
          run: terraform plan -out=tfplan

        - name: Terraform Apply
          run: terraform apply -auto-approve tfplan